apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-beregn-forskudd-rest
  namespace: bidrag
  labels:
    team: bidrag
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-beregn-forskudd-rest.intern.nav.no
  env:
    - name: BIDRAGGCPPROXY_URL
      value: https://bidrag-gcp-proxy.intern.nav.no
    - name: BIDRAGGCPPROXY_SCOPE
        value: prod-fss.bidrag.bidrag-gcp-proxy
