apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: { { azure.cucumber_cloud_app } }
          cluster: { { azure.cucumber_cloud_cluster } }
          namespace: bidrag
    outbound:
      external:
        - host: { { azure.bidraggcpproxy_url } }
  image: {{ image }}
  liveness:
    path: /bidrag-beregn-forskudd-rest/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-beregn-forskudd-rest/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-beregn-forskudd-rest/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: BIDRAGGCPPROXY_URL
      value: https://{{ azure.bidraggcpproxy_url }}
    - name: BIDRAGGCPPROXY_SCOPE
      value: {{ azure.bidraggcpproxy_scope }}
