apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-beregn-forskudd-rest
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: bidrag-ui
          namespace: bidrag
          cluster: prod-fss
        - application: bidrag-behandling
          namespace: bidrag
          cluster: prod-gcp
    outbound:
      external:
        - host: bidrag-sjablon.prod-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-beregn-forskudd-rest.intern.nav.no
  env:
    - name: BIDRAGSJABLON_URL
      value: https://bidrag-sjablon.prod-fss-pub.nais.io
    - name: BIDRAGSJABLON_SCOPE
      value: prod-fss.bidrag.bidrag-sjablon
