BIDRAGGCPPROXY_URL: https://bidrag-gcp-proxy.dev-fss-pub.nais.io

springdoc:
  packages-to-scan: no.nav.bidrag.beregn.forskudd.rest.controller
  swagger-ui:
    path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
      client:
        registration:
          bidraggcpproxy:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://${BIDRAGGCPPROXY_SCOPE}/.default
        provider:
          aad:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}

# OIDC
no.nav.security.jwt:
  issuer:
    aad:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

---
# Profil for lokal kjøring
spring.config.activate.on-profile: local

# Lokal profil bruker selvstendige wiremocks
wiremock.server:
  files: classpath:/__files
  stubs: classpath:/wiremock_stubs

---
# Profil for integrasjonstest
spring.config.activate.on-profile: integrationtest
SJABLON_URL: http://localhost:8096/bidrag-sjablon
