SJABLON_URL: https://bidrag-sjablon-q1.nais.preprod.local/bidrag-sjablon

server:
  servlet:
    context-path: /bidrag-beregn-forskudd-rest
management:
  endpoints:
    web:
      exposure:
        include: "*"
