springdoc:
  packages-to-scan: no.nav.bidrag.beregn.forskudd.rest.controller
  swagger-ui:
    path: /

# OIDC
no.nav.security.jwt:
  issuer:
    aad:
      discovery-url: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

# Inkluderer alle felter i JSON-responsen
spring:
  jackson:
    default-property-inclusion: ALWAYS