SJABLON_URL: https://bidrag-sjablon-q1.nais.preprod.local/bidrag-sjablon

server:
  servlet:
    context-path: /bidrag-beregn-forskudd-rest
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
# Profil for lokal kjøring
spring.config.activate.on-profile: local

# Lokal profil bruker selvstendige wiremocks
wiremock.server:
  files: classpath:/__files
  stubs: classpath:/wiremock_stubs

---
# Profil for integrasjonstest
spring.config.activate.on-profile: integrationtest
SJABLON_URL: http://localhost:8096/bidrag-sjablon
