name: continious integration
on:
  push:
    branches:
      - '**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/bidrag-beregn-forskudd-rest:${{ github.sha }}

jobs:

  build:
    name: Build with maven and docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '13'
      - run: env
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/maven@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v1.0.4
      - run: mvn install -B -e
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy_dev:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    if: github.ref != 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - name: Deploy to dev-fss, default namespace
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=default,sjablonurl=https://bidrag-sjablon.nais.preprod.local/bidrag-sjablon,ingress=https://bidrag-beregn-forskudd-rest.nais.preprod.local/
      - name: Deploy to dev-fss, namespace q1
        if: github.ref != 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=q1,sjablonurl=https://bidrag-sjablon-q1.nais.preprod.local/bidrag-sjablon,ingress=https://bidrag-beregn-forskudd-rest-q1.nais.preprod.local/

  bump_dev_version:
    runs-on: ubuntu-latest
    name: bump SNAPSHOT version
    if: github.ref == 'refs/heads/master'
    needs: deploy_dev

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn release:update-versions
      - run: |
          BUMPED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${BUMPED_VERSION}
        id: snapshot
      - uses: navikt/bidrag-git/commit@v3.0.3
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_prod:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    if: github.ref == 'refs/heads/release'
    needs: build

    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/nais-p.yaml
          VAR: namespace=default

  tag_prod_deploy:
    runs-on: ubuntu-latest
    name: Tag latest deploy to prod
    needs: deploy_prod

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: |
          TAG_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          echo ::set-output name=tag::${TAG_VERSION}
        id: release
      - uses: navikt/bidrag-git/tag@v3.0.4
        with:
          tag_message: Releasing version ${{ steps.release.outputs.tag }}
          tag: ${{ steps.release.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
